export const emojiList = [
    { symbol: "😀", name: "smile face" },
    { symbol: "😄", name: "smile face" },
    { symbol: "😁", name: "smile face" },
    { symbol: "😅", name: "smile face" },
    { symbol: "🤣", name: "smile laughing face" },
    { symbol: "😂", name: "smile tears of joy" },
    { symbol: "😍", name: "smile face with heart-eyes" },
    { symbol: "😎", name: "smile face with sunglasses" },
    { symbol: "🥺", name: "pleading face" },
    { symbol: "🤔", name: "thinking face" },
    { symbol: "🔥", name: "fire" },
    { symbol: "❤️", name: "red heart" },
    {symbol: "💀", name: "skull"},
    { symbol: "😒", name: "anger face" },
    { symbol: "😞", name: "sad face" },
    { symbol: "😈", name: "devil face" },
    { symbol: "😅", name: "smile face" },
    { symbol: "😭", name: "crying face" },
    { symbol: "🤯", name: "exploding face" },
    { symbol: "😷", name: " face with medical mask" },
    { symbol: "🤧", name: "sneezing face" },
    { symbol: "🤮", name: "vomting face" },
    { symbol: "🤒", name: "thermometer face" },
    { symbol: "🥴", name: "woozy face" },
    { symbol: "😑", name: "expression less face" },
    { symbol: "😰", name: "anixous face" },
    { symbol: "👽", name: "alien" },
    {symbol: "🤖", name: "robot"},
    
    { symbol: "🫶", name: "heart hands" },
    { symbol: "🤲", name: "plam up hands" },
    { symbol: "👐", name: "open hands" },
    { symbol: "👏", name: "clapping hands" },
    { symbol: "🤝", name: "handshake" },
    { symbol: "👍", name: "thumbs up hand" },
    { symbol: "👎", name: "thumbs down hand" },
    { symbol: "👊", name: "oncomming fist hand" },
    { symbol: "✊", name: "raised fist hand" },
    { symbol: "🤞", name: " crossed fingers hand" },
    { symbol: "✌️", name: " victory hand" },
    { symbol: "🤙", name: "call me hand" },
    { symbol: "👋", name: " waving hand" },
    { symbol: "✋", name: "raised hand" },
    {symbol: "🫵", name: "index pointing hand"},

    { symbol: "👶", name: "human face" },
    { symbol: "🧒", name: "human face" },
    { symbol: "👧", name: "human face" },
    { symbol: "👩", name: "human face" },
    { symbol: "🧑‍🦰", name: "human face" },
    { symbol: "👩‍🦰", name: "human face" },
    { symbol: "👱‍♀️", name: "human face" },
    { symbol: "👱‍♂️", name: "human face" },
    { symbol: "🧔‍♂️", name: "human face" },
    { symbol: "🧔", name: "human face " },
    { symbol: "👩‍🦲", name: " human face" },
    { symbol: "👨‍🦲", name: "human face" },
    { symbol: "👨‍🦳", name: "human face " },
    { symbol: "👴", name: "human face" },
    {symbol: "👨", name: "human face"},
    { symbol: "👱‍♀️", name: " human face" },
    { symbol: "👨‍🦰", name: "human face" },
    { symbol: "😼", name: "smile cat " },
    { symbol: "😹", name: "crying cat" },
    {symbol: "😻", name: "love cat"},




    


];

export default emojiList;
